# Importing libraries for data preprocessing

In [27]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing Dataset

In [28]:
dataset = pd.read_csv('Data.csv')
# iloc-- index ; dataset.iloc[row, cols].values
features_X = dataset.iloc[:,:-1].values
dependent_Y = dataset.iloc[:,-1].values

In [29]:
print(features_X)
print(dependent_Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Taking care of missing data

In [23]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# imputer.fit(features_X[:,1:3])
features_X[:,1:3]=imputer.fit_transform(features_X[:,1:3])
print(features_X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


# Encoding categorical data

To change categorical data(first column) for both independent and dependent variable into numerical values.

## Independent Variables

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])] ,remainder='passthrough')
features_X = np.array(ct.fit_transform(features_X))
# print(features_X)

# Dependent Variables

In [31]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dependent_Y= le.fit_transform(dependent_Y)
print(dependent_Y)

[0 1 0 0 1 1 0 1 0 1]


# Splitting Dataset into training set and Testing set